name: Publish Package
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
permissions:
  id-token: write   # NPM
  contents: write   # Release
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm ci
          npm run setup
          npm run esbuild
          npm run test
      - run: ./publish.sh
